### ISSUE TITLE
stoken是哪个？

### ISSUE THREAD

**Issue by Xiao-yux** [monsterxcn/nonebot-plugin-gsmaterial#11]
![image](https://github.com/monsterxcn/nonebot-plugin-gsmaterial/assets/79674967/65242939-d4c8-4d31-846b-2fdea2183da2)
我这只看到了ltoken

**Comment by monsterxcn** [comment]
网页上看不到，需要手机 APP 抓包，推荐卸载原版米游社，安装 [@HolographicHat/GetToken](https://github.com/HolographicHat/GetToken) 修补过的米游社，在“我的”页面右上角，小钥匙图标点进去，勾选 SToken 获取

https://github.com/HolographicHat/GetToken/releases/download/2.60.1/miyoushe-361-lspatched.apk
