### ISSUE TITLE
显示三星武器设置不成功

### ISSUE THREAD

**Issue by liuzj288** [monsterxcn/nonebot-plugin-gsmaterial#2]
![image](https://user-images.githubusercontent.com/13833404/189361621-d966f2f0-a8e9-4e11-8268-e903164d4efb.png)
已经谢了这个参数怎么还是没输出三星武器

**Comment by monsterxcn** [comment]
Bot 加载的是这个文件的环境变量吗？ Bot 启动阶段日志发出来看看
