### ISSUE TITLE
订阅推送时间的环境变量如何填写？

### ISSUE THREAD

**Issue by Kiana1314** [monsterxcn/nonebot-plugin-gsmaterial#3]
萌新一枚不会弄 没报错也没生效
或者大佬能加个设置时间的指令吗

 
![K6}$%`)I{~I%%FP 57GI58P](https://user-images.githubusercontent.com/107671434/191626353-fb2ab8dc-3fc8-4ee0-b760-458b7a8e260a.png)

**Comment by monsterxcn** [comment]
应该是这样：

```
gsmaterial_scheduler="7:07"
```
