### ISSUE TITLE
启动时 `thisCfg[key].split(",")` 处报错 KeyError 但是插件指令还能正常使用

### ISSUE THREAD

**Issue by Kiana1314** [monsterxcn/nonebot-plugin-gsmaterial#4]
![111](https://user-images.githubusercontent.com/107671434/193615396-d005bf58-a6b9-421b-be3c-fd6561420a8b.jpg)

**Comment by monsterxcn** [comment]
怪，是绘制周本图片出错了，看看插件生成的 config.json 里面 weekly 存的内容是啥样的？

**Comment by Kiana1314** [comment]
![HSXMI3LQLMKQV917U00PA{O](https://user-images.githubusercontent.com/107671434/193900863-b525c6e8-c8d0-4f26-b467-8ecfd36c6dd0.png)

**Comment by Kiana1314** [comment]
更新后没有报错了 谢谢大佬
