### ISSUE TITLE
资源下载出错

### ISSUE THREAD

**Issue by Kiana1314** [monsterxcn/nonebot-plugin-gsmaterial#5]
![image](https://user-images.githubusercontent.com/107671434/199022283-b1654061-272c-46fe-ba47-a0ff96fd57c9.png)

**Comment by monsterxcn** [comment]
1. 图片下载的问题要安柏计划上游更新，是散兵周本材料的三个图片。
2. `IndexError` 是我这边写的有问题，等散兵周本的信息确定下来我一起修复。

其他的功能应该暂时都正常吧？截图这个问题麻烦耐心等两天😘

**Comment by monsterxcn** [comment]
哦吼，看了下代码，图片下载失败也是我的锅，我拼接周本那个链接的时候忘记带上 `.png` 后缀了！
