### ISSUE TITLE
安柏计划 材料列表出错

### ISSUE THREAD

**Issue by MonsterLaplace** [monsterxcn/nonebot-plugin-gsmaterial#6]
11-15 16:38:16 [INFO] websockets | connection open
11-15 16:38:16 [INFO] nonebot_plugin_gsmaterial | Genshin Material 正在执行数据更新...
11-15 16:38:26 [INFO] nonebot_plugin_gsmaterial | 安柏计划 材料列表 接口请求出错，正在重试...
11-15 16:38:29 [INFO] nonebot_plugin_gsmaterial | Genshin Material 数据初始化 / 更新完成！

**Comment by monsterxcn** [comment]
这不是最后完成了吗？你发命令不能正常返回吗？

这行只是提示你访问安柏计划出问题了，正在重试。如果彻底失败应该不会有下面那行的，大概……

**Comment by MonsterLaplace** [comment]
> 这不是最后完成了吗？你发命令不能正常返回吗？
> 
> 这行只是提示你访问安柏计划出问题了，正在重试。如果彻底失败应该不会有下面那行的，大概……

谢谢，目前除了这个 报错，暂时没遇到什么问题  。
