### ISSUE TITLE
[py-plugin] 无法正确获取时区，插件能否定义个时区变量

### ISSUE THREAD

**Issue by liuzj288** [monsterxcn/nonebot-plugin-gsmaterial#9]
可以参考
https://github.com/he0119/nonebot-plugin-wordcloud
这个插件自定义的
wordcloud_timezone
变量

**Comment by monsterxcn** [comment]
什么报错发一下

**Comment by liuzj288** [comment]
> 

没有报错，但是获取的时区是伦敦时区，导致所有指令都出现时间错位
![image](https://user-images.githubusercontent.com/13833404/211003287-562d0fbd-c9c0-42d0-af9a-6a6a91b363da.png)

**Comment by monsterxcn** [comment]
应该是你服务器系统时区的问题，你可以找找怎么改。

原生 NoneBot2 的话有那几个 .env 文件，加 `TZ=Asia/Shanghai` 也许有用。py-plugin 的话… 你试试在 config.yaml 里加一行 `tz: Asia/Shanghai`？

先尝试下💦，额外的配置项这两天我再看看

**Comment by monsterxcn** [comment]
能看看你 `data/gsmaterial` 目录下的 config.json 吗？

**Comment by monsterxcn** [comment]
呃呃还有一点，你这图片是 `#周一素材` 触发的？？插件根本不会响应这样的指令啊，要用也是 `材料周一` 这样

**Comment by liuzj288** [comment]
> 呃呃还有一点，你这图片是 `#周一素材` 触发的？？插件根本不会响应这样的指令啊，要用也是 `材料周一` 这样

用了alias插件
alias 周一素材="素材周一"

**Comment by monsterxcn** [comment]
好强，还有这种插件，我都不知道（（

明天我试着加一下那个时区配置，你可以等明天更新插件填写配置试试

**Comment by monsterxcn** [comment]
ffd1bdc7fbd4da0cc7454c57dab2d73a2e6e4d22 添加了时区配置，更新插件 0.2.3 版本即可，不额外添加环境变量配置的话默认是上海时区，希望能解决你的问题。

**Comment by liuzj288** [comment]
这个插件，可以在不修改源代码情况下自定义命令的，挺好用的
https://github.com/noneplugin/nonebot-plugin-alias

**Comment by monsterxcn** [comment]
既然有 [nonebot-plugin-alias](https://github.com/noneplugin/nonebot-plugin-alias) 的话，你就先用它吧，看你的截图似乎用起来体验也还蛮不错嘛。我这边暂时不打算支持该功能了。

另外建议不要回复与 issue 无关的话题哦，这里毕竟不是 QQ 群什么的。如果时区的问题解决了，那么你就可以点下面的 close 将这个 issue 关闭了🥰

**Comment by monsterxcn** [comment]
在某 QQ 群碰巧遇到，根据你给我的反馈，当日材料已经正常，但是指定周几依然比实际要早一天？

我反复检查了代码，未发现该功能和时区有什么联系，其指定方式完全靠对输入的提取识别，并且我自己这边测试是没问题的。

你本身使用的是 Yunzai + py-plugin 并使用 nonebot-plugin-alias 对插件输入进行了修改，情况可能有些复杂而且不具备普遍性。另外在整个 issue 交流过程中你完全没提交过一条有用的日志，令我十分头疼，对你这个问题目前能解决的程度也就到这里了。

综上，我不打算再继续跟进这个 issue 直到有人能给我点对 debug 有用的信息，一直没有的话我将 close 此 issue。

**Comment by liuzj288** [comment]
> 在某 QQ 群碰巧遇到，根据你给我的反馈，当日材料已经正常，但是指定周几依然比实际要早一天？
> 
> 我反复检查了代码，未发现该功能和时区有什么联系，其指定方式完全靠对输入的提取识别，并且我自己这边测试是没问题的。
> 
> 你本身使用的是 Yunzai + py-plugin 并使用 nonebot-plugin-alias 对插件输入进行了修改，情况可能有些复杂而且不具备普遍性。另外在整个 issue 交流过程中你完全没提交过一条有用的日志，令我十分头疼，对你这个问题目前能解决的程度也就到这里了。
> 
> 综上，我不打算再继续跟进这个 issue 直到有人能给我点对 debug 有用的信息，一直没有的话我将 close 此 issue。

今天更新之后问题解决了，应该是之前没有导入apscheduler设置的原因吧
![image](https://user-images.githubusercontent.com/13833404/212033838-e490affb-9c13-42e0-bcc6-fbccc2a1ac06.png)
![image](https://user-images.githubusercontent.com/13833404/212034018-64ed51d6-667f-48d6-ad1c-76a1263dbb0c.png)
